// Generated by CIRCT firtool-1.62.1
module AutoTilingWeight(
  input         clock,
                reset,
                io_enable,
                io_nextRowEnable,
  output [16:0] io_rdAddr_0,
                io_rdAddr_1,
                io_rdAddr_2,
                io_rdAddr_3,
                io_rdAddr_4,
                io_rdAddr_5,
                io_rdAddr_6,
                io_rdAddr_7,
                io_rdAddr_8,
                io_rdAddr_9,
                io_rdAddr_10,
                io_rdAddr_11,
                io_rdAddr_12,
                io_rdAddr_13,
                io_rdAddr_14,
                io_rdAddr_15,
  output        io_addrValid_0,
                io_addrValid_1,
                io_addrValid_2,
                io_addrValid_3,
                io_addrValid_4,
                io_addrValid_5,
                io_addrValid_6,
                io_addrValid_7,
                io_addrValid_8,
                io_addrValid_9,
                io_addrValid_10,
                io_addrValid_11,
                io_addrValid_12,
                io_addrValid_13,
                io_addrValid_14,
                io_addrValid_15
);

  reg  [16:0] tileStartX;
  reg  [16:0] tileStartY;
  reg  [16:0] rowNum;
  wire [21:0] _GEN = {1'h0, tileStartY, 4'h0};
  wire [16:0] _GEN_0 = {tileStartX[12:0] * 13'h93, 4'h0};
  wire [16:0] _GEN_1 = {tileStartY[12:0], 4'h0};
  wire [16:0] _io_rdAddr_15_T_5 = rowNum * 17'h93;
  wire [21:0] _GEN_2 = {1'h0, tileStartX, 4'h0};
  wire [21:0] _GEN_3 = {5'h0, rowNum};
  wire [21:0] _rowAddr_T_1 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_3 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_5 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_7 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_9 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_11 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_13 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_15 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_17 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_19 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_21 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_23 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_25 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_27 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_29 = _GEN_2 + _GEN_3;
  wire [21:0] _rowAddr_T_31 = _GEN_2 + _GEN_3;
  always @(posedge clock) begin
    if (reset) begin
      tileStartX <= 17'h0;
      tileStartY <= 17'h0;
      rowNum <= 17'h0;
    end
    else begin
      automatic logic isLastRowInTile;
      automatic logic isLastTileInRow;
      isLastRowInTile = rowNum == 17'hF;
      isLastTileInRow = tileStartY == 17'h9;
      if (io_enable & isLastRowInTile & isLastTileInRow & io_nextRowEnable)
        tileStartX <= tileStartX == 17'h3 ? 17'h0 : tileStartX + 17'h1;
      if (io_enable & isLastRowInTile) begin
        if (isLastTileInRow)
          tileStartY <= 17'h0;
        else
          tileStartY <= tileStartY + 17'h1;
      end
      if (io_enable) begin
        if (isLastRowInTile)
          rowNum <= 17'h0;
        else
          rowNum <= rowNum + 17'h1;
      end
    end
  end // always @(posedge)
  assign io_rdAddr_0 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 : 17'h0;
  assign io_rdAddr_1 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h1 : 17'h0;
  assign io_rdAddr_2 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h2 : 17'h0;
  assign io_rdAddr_3 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h3 : 17'h0;
  assign io_rdAddr_4 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h4 : 17'h0;
  assign io_rdAddr_5 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h5 : 17'h0;
  assign io_rdAddr_6 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h6 : 17'h0;
  assign io_rdAddr_7 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h7 : 17'h0;
  assign io_rdAddr_8 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h8 : 17'h0;
  assign io_rdAddr_9 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'h9 : 17'h0;
  assign io_rdAddr_10 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'hA : 17'h0;
  assign io_rdAddr_11 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'hB : 17'h0;
  assign io_rdAddr_12 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'hC : 17'h0;
  assign io_rdAddr_13 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'hD : 17'h0;
  assign io_rdAddr_14 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'hE : 17'h0;
  assign io_rdAddr_15 = io_enable ? _GEN_0 + _GEN_1 + _io_rdAddr_15_T_5 + 17'hF : 17'h0;
  assign io_addrValid_0 = io_enable & ~((|(_rowAddr_T_1[21:6])) | _GEN > 22'h92);
  assign io_addrValid_1 = io_enable & ~((|(_rowAddr_T_3[21:6])) | _GEN + 22'h1 > 22'h92);
  assign io_addrValid_2 = io_enable & ~((|(_rowAddr_T_5[21:6])) | _GEN + 22'h2 > 22'h92);
  assign io_addrValid_3 = io_enable & ~((|(_rowAddr_T_7[21:6])) | _GEN + 22'h3 > 22'h92);
  assign io_addrValid_4 = io_enable & ~((|(_rowAddr_T_9[21:6])) | _GEN + 22'h4 > 22'h92);
  assign io_addrValid_5 = io_enable & ~((|(_rowAddr_T_11[21:6])) | _GEN + 22'h5 > 22'h92);
  assign io_addrValid_6 = io_enable & ~((|(_rowAddr_T_13[21:6])) | _GEN + 22'h6 > 22'h92);
  assign io_addrValid_7 = io_enable & ~((|(_rowAddr_T_15[21:6])) | _GEN + 22'h7 > 22'h92);
  assign io_addrValid_8 = io_enable & ~((|(_rowAddr_T_17[21:6])) | _GEN + 22'h8 > 22'h92);
  assign io_addrValid_9 = io_enable & ~((|(_rowAddr_T_19[21:6])) | _GEN + 22'h9 > 22'h92);
  assign io_addrValid_10 =
    io_enable & ~((|(_rowAddr_T_21[21:6])) | _GEN + 22'hA > 22'h92);
  assign io_addrValid_11 =
    io_enable & ~((|(_rowAddr_T_23[21:6])) | _GEN + 22'hB > 22'h92);
  assign io_addrValid_12 =
    io_enable & ~((|(_rowAddr_T_25[21:6])) | _GEN + 22'hC > 22'h92);
  assign io_addrValid_13 =
    io_enable & ~((|(_rowAddr_T_27[21:6])) | _GEN + 22'hD > 22'h92);
  assign io_addrValid_14 =
    io_enable & ~((|(_rowAddr_T_29[21:6])) | _GEN + 22'hE > 22'h92);
  assign io_addrValid_15 =
    io_enable & ~((|(_rowAddr_T_31[21:6])) | _GEN + 22'hF > 22'h92);
endmodule

